CREATE OR REPLACE DATABASE SNOWFLAKE_DEMO_DB;

CREATE OR ALTER WAREHOUSE SNOWFLAKE_DEMO_WH
  WAREHOUSE_TYPE = STANDARD
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE;

CREATE OR REPLACE ROLE snowflake_demo_owner;

GRANT ROLE snowflake_demo_owner TO ROLE sysadmin;

GRANT OWNERSHIP ON DATABASE SNOWFLAKE_DEMO_DB TO snowflake_demo_owner;

USE ROLE snowflake_demo_owner;

USE DATABASE SNOWFLAKE_DEMO_DB;

CREATE SCHEMA DEMO_TABLES;
