CREATE OR REPLACE DATABASE SNOWFLAKE_DEMO_DB;

CREATE OR ALTER WAREHOUSE SNOWFLAKE_DEMO_WH
  WAREHOUSE_TYPE = STANDARD
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE;

CREATE OR REPLACE ROLE snowflake_demo_owner;

!prompt vPassword "Enter password for new user";

CREATE OR REPLACE USER snowflake_demo_admin
  PASSWORD = '&vPassword'
  DEFAULT ROLE = snowflake_demo_owner
  DEFAULT WAREHOUSE = SNOWFLAKE_DEMO_WH;
